name: radio-homework

networks:
  public-tier:
  private-tier:
    internal: true

configs:
  nginx_default:
    file: docker/radio/virtual_host.conf
  radio_liq:
    file: docker/radio/radio.liq
  icecast_xml:
    file: icecast/icecast.xml

services:
  icecast:
    container_name: icecast
    build: icecast
    restart: unless-stopped
    configs:
      - source: icecast_xml
        target: /etc/icecast2/icecast.xml
    networks:
      private-tier:

  liquidsoap:
    container_name: liquidsoap
    image: savonet/liquidsoap:v2.2.5
    restart: unless-stopped
    depends_on:
      - icecast
    networks:
      private-tier:
    configs:
      - source: radio_liq
        target: /etc/radio/radio_liq
    command: [
      "/etc/radio/radio_liq"
    ]

  server:
    container_name: nginx
    image: nginx:1.27-bookworm
    restart: unless-stopped
    depends_on:
      - icecast
    networks:
      private-tier:
      public-tier:
    ports:
      - "80:80"
    configs:
      - source: nginx_default
        target: /etc/nginx/conf.d/default.conf